version: '3.7'
services:
  web:
    image: python:latest
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    working_dir: /app
    command: python app.py
networks:
  default:
    name: apollo
    external: true

